# Generated by Django 4.0.3 on 2022-04-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('disponible', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now=True, null=True)),
                ('imagen_64', models.CharField(default='https://seedpaybuck.s3.sa-east-1.amazonaws.com/usuarios/71276688-7770-4a41-a7a2-24bd867043a1.jpg', max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'producto',
            },
        ),
    ]
